### ISSUE TITLE
Prometheus targets problem

### ISSUE THREAD

**Issue by mustafayildirim** [vfarcic/cloud-provisioning#1]
Hi, I am reading your book that devops-toolkit 2.1.

At "Collecting Metrics and Monitoring The Cluster"
I am trying your example but Prometheus Target - cadvisor and node Enpoints are wrong. I think beacuse of dns.

I am using latest version of cloud-provisioning repo.

I attached the screenshots.
![docker-node-ls](https://cloud.githubusercontent.com/assets/2341474/20432773/66d89622-ada9-11e6-887d-9091b8405123.jpeg)
![docker-network-ls](https://cloud.githubusercontent.com/assets/2341474/20432778/6b5ff514-ada9-11e6-9418-6dc2715ce417.jpeg)
![docker-service-ls](https://cloud.githubusercontent.com/assets/2341474/20432780/701ce88c-ada9-11e6-9c67-8b76ffa759d1.jpeg)

![prometheus](https://cloud.githubusercontent.com/assets/2341474/20432690/04262260-ada9-11e6-9ee1-e0ad0416b8ca.jpeg)

Is there anything missed?

**Comment by vfarcic** [comment]
Can you send me the output of:

``` sh
docker service ps cadvisor

docker service ps node-exporter
```

**Comment by mustafayildirim** [comment]
I tried again. Same issue
Here are they.

`docker service ps cadvisor`
![cadvisor](https://cloud.githubusercontent.com/assets/2341474/20434006/aa76b616-adae-11e6-8d89-2ace4bd8df0c.jpeg)

`docker service ps node-exporter`
![node-exporter](https://cloud.githubusercontent.com/assets/2341474/20434043/d6f4220a-adae-11e6-9c63-832daae45af5.jpeg)

**Comment by vfarcic** [comment]
Can we have a Skype or HangOuts call and share your screen? Would sometime tomorrow suit you?

**Comment by mustafayildirim** [comment]
Yes we can. My timezone is UTC+3. 
I can available tomorrow after 6pm (UTC+3)

**Comment by vfarcic** [comment]
Great!

Can you send an calendar invite. That way I won't forget it :)

**Comment by vfarcic** [comment]
Hi,

I completely missed it. I'm truly sorry for that. I'm currently in UK and I
can connect sometime after 19h GMT if that would suit you. If it does, can
you please send an invite so that I get a notification?

**Comment by mustafayildirim** [comment]
Hi,

I just sent an invitation you mail address.
