### ISSUE TITLE
swarm creation: VIRTUALBOX_SHARE_FOLDER issue on Windows

### ISSUE THREAD

**Issue by albers** [vfarcic/cloud-provisioning#11]
@vfarcic As you already mention in your book _The Devops 2.1 Toolkit_, chapter "Setting Up Continuous Delivery Clusters", there is an issue with the volume mounts in current versions of docker-machine and VirtualBox on Windows.
Here's what I found out on this subject using Docker Toolbox 1.13.1 (i.e. Docker Machine 0.9.0 & VirtualBox 5.1.14) on Windows 7:

Your code uses the current directory mounted as a VirtualBox shared folder in several VMs in order to share registry data between the testing and production swarms.
Sadly, **mounting custom directories as shared folders on Windows is broken in docker-machine 0.9.0.**
Only the default mount of the user's home directory works.

This leads to two problems:
- The VMs do not contain the path `$PWD`. `docker service create` fails because of an invalid mount option.
- No data is shared between the swarms.

To verify the shared directory issue, create two machines (xx is a substitute for your user name):
```bash
docker-machine create --driver virtualbox default-shared-folder
docker-machine create --driver virtualbox --virtualbox-share-folder "/c/Users/xx:/XXX" custom-shared-folder
```
In the _Oracle VM VirtualBox Manager_, check the VM details. `default-shared-folder` has one shared folder, `custom-shared-folder` has none.

The reason for the failed creation of shared folders is that `VIRTUALBOX_SHARE_FOLDER` and `--virtualbox-share-folder` both have a `source:destination` syntax, where `source` on Windows machines **must** be given as `c:/...`. The extra colon causes parsing of the argument to fail, see https://github.com/docker/machine/pull/3975. This is fixed in https://github.com/docker/machine/pull/3975. Using a custom build of `docker-machine`, I was able to create a custom mount of the current directory with
```bash
docker-machine create --driver virtualbox --virtualbox-share-folder "$(cygpath -m $PWD):$PWD" custom-shared-folder
```
Because `$pwd` returns the path in `/c/...` format, some kind of conversion is needed. This example will not work on Macs. We need OS specific treatment.

I see the following solutions:
- create separate scripts for Windows and Mac, the Windows scripts using conversion with `cygpath` (available in Docker Toolbox) or variable substitutions.
- enhance the existing scripts with OS specific conversion.
- create an issue in Docker-Machine that on Windows, paths like `/c/...` should be converted to `c:/...`.
- Remove `VIRTUALBOX_SHARE_FOLDER="$PWD:$PWD"` from the scripts. All users will have to work in a subdir of their homedir (like in `vfarcic/go-demo`). This is the only solution that works with the current Docker Machine.

Hope this information is helpful for you.

**Comment by albers** [comment]
[Docker machine 0.10.0](https://github.com/docker/machine/releases/tag/v0.10.0) is out now. It properly treats `--virtualbox-share-folder "C:/Users/xx:/c/Users/xx"` (`$(cygpath -m $PWD):$PWD` in user xx's home dir).

**Comment by vfarcic** [comment]
@albers Sorry for not responding earlier. Too much work and too little time...

I removed the `VIRTUALBOX_SHARE_FOLDER` env. var. The book already explains that the `ms-lifecycle` project should be clone in one of system user's subdirectories. I think this should be safe on Windows and I know it works on OSX. Soon we'll push a solution for Linux that will haven an `if OS == Linux` conditional.

**Comment by albers** [comment]
That's great! Thanks.
