### ISSUE TITLE
update swarm deploy to support Terraform v0.9.1

### ISSUE THREAD

**Issue by bbenson29** [vfarcic/cloud-provisioning#14]
When deploying swarm using terraform v0.9.1 output variables are not showing but with v0.8.5 everything works as it show do.

After deploying the first manager node with 
`terraform apply \
        -target aws_instance.swarm-manager \
        -var swarm_init=true    \
        -var swarm_managers=1`
No output variables are displayed.

**Comment by vfarcic** [comment]
That is caused by a bug in the recent Terraform releases. HashiCorp will, hopefully, fix it soon. In the meantime, the solution is to revert to the version 0.8.8 or to execute the `apply` command twice.
