### ISSUE TITLE
DevOps2.1: Automating Continuous Deployment Flow WithJenkins

### ISSUE THREAD

**Issue by robert0714** [vfarcic/cloud-provisioning#17]
I'm following along with the leanpub _DevOps2.1 Toolkit._ So far so good, but now the jenkins-agent service creating is proving difficult. With the swarm running:

```
export USER=admin
export PASSWORD=admin

docker service create --name jenkins-agent \
-e COMMAND_OPTIONS="-master \
http://$(docker-machine ip swarm-1):8082/jenkins \
-username $USER -password $PASSWORD \
-labels 'docker' -executors 5" \
--mode global \
--constraint 'node.labels.env == jenkins-agent' \
--mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock" \
--mount "type=bind,source=$HOME/.docker/machine/machines,target=/machines" \
--mount "type=bind,source=/workspace,target=/workspace" \
vfarcic/jenkins-swarm-agent
```
If the line ```--mount "type=bind,source=$HOME/.docker/machine/machines,target=/machines" \``` exist, it 'll show ERROR  ```"invalid mount config for type…"```

```
[weblogic@robertleepc cloud-provisioning]$ docker service  ps jenkins-agent 
ID            NAME                                         IMAGE                               NODE          DESIRED STATE  CURRENT STATE           ERROR                             PORTS
s1za0gvjjrri  jenkins-agent.meb853xkpo07kzz618yct2vua      vfarcic/jenkins-swarm-agent:latest  swarm-test-1  Ready          Rejected 3 seconds ago  "invalid mount config for type…"  
6ik84sdnmml6   \_ jenkins-agent.meb853xkpo07kzz618yct2vua  vfarcic/jenkins-swarm-agent:latest  swarm-test-1  Shutdown       Rejected 8 seconds ago  "invalid mount config for type…"  
sw49sebngqv9   \_ jenkins-agent.meb853xkpo07kzz618yct2vua  vfarcic/jenkins-swarm-agent:latest  swarm-test-1  Shutdown       Rejected 8 seconds ago  "invalid mount config for type…"  
```
I need the line  ```--mount "type=bind,source=$HOME/.docker/machine/machines,target=/machines" \``` exist, it 'll show ERROR  ``` in order to let Jenkins execute the Job "Pipeline go-demo"(scripts/go-demo-pull.groovy)!
```
withEnv([
        "DOCKER_TLS_VERIFY=1",
        "DOCKER_HOST=tcp://${env.PROD_LIKE_IP}:2376",
        "DOCKER_CERT_PATH=/machines/${env.PROD_LIKE_NAME}"
])
```

I'm using Centos 7.3 ( 3.10.0-514.10.2.el7.x86_64)
Version info:
```
[weblogic@robertleepc cloud-provisioning]$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:36:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 16:58:30 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by vfarcic** [comment]
Can you please confirm that you are running the commands from your user directory (or subdirectory)? Please paste the path.

Also, it would be useful if you can SSH into one of the machines and check whether user dir is mounted or not.

**Comment by robert0714** [comment]
Thank  you for  your advice !!!

 I  tried it in my Mac laptop . It worked OK!! But sadly , it did not work in Centos 7.3 !
I tried to compared the differences , and then found out as below  : 
(1) swarm-test-1 In Mac
![2017-04-01_044603_2](https://cloud.githubusercontent.com/assets/2332674/24569289/0b0ee9d8-1698-11e7-9665-e08bb28eaeee.png)

(2)swarm-test-1 in Centos 7.3
![2017-04-01_044603](https://cloud.githubusercontent.com/assets/2332674/24569330/2ff818a0-1698-11e7-8041-ab0d61b34a2f.png)

It mount host user directory not completely in CentOS

I  only found related issue ( https://github.com/docker/machine/issues/3234  )

I have a problem !   in Ubuntu ??  It will ??

**Comment by vfarcic** [comment]
It should work in Ubuntu (at least on newer version of Docker Machine). A couple of members in http://slack.devops20toolkit.com/ passed all the examples from the book using Ubuntu.

I'm not using CentOS on my laptop so cannot easily confirm/deny that the issue you mentioned the same. I did run Swarm on CentOS/RedHat but that was on "real" servers. In such a scenario, mounting a network drive follows a different approach and depends on hosting vendor you're using. You'll see a few examples later on in later chapters.

**Comment by robert0714** [comment]
Thank you so so much   for your always  kind help :)

**Comment by yaffol** [comment]
I would add that I have just experienced this problem under Ubuntu 16.04 and docker-machine version 0.11.0, build 5b27455

I fixed it temporarily by altering the shared folder settings for the node swarm-test-1 in the Virtualbox GUI, and removing the mount is was automatically creating

`/home/patrick/dev/dailyinfo/swarm/cloud-provisioning on /home/patrick/dev/dailyinfo/swarm/cloud-provisioning type vboxsf (rw,nodev,relatime)`

and replacing it with a mount of my /home/patrick directory

`/home/patrick on /home/patrick type vboxsf (rw,nodev,relatime)`

**Comment by naslanidis** [comment]
@rpawsey 

I'm on Ubuntu 16.04 and docker-machine 10 and have the same issue as yourself. Thanks for the work around.

**Comment by jorgebo10** [comment]
I have just experienced it too. On Ubuntu 16.04 and docker-machine version 0.13.0, build 9ba6da9 .

**Comment by vfarcic** [comment]
@jorgebo10 Did you try the solution from @patrickvale ?

**Comment by jorgebo10** [comment]
i tried but without success. I'll try to provide more information. Thanks

**Comment by jorgebo10** [comment]
I found the problem. There was a typo while copy and pasting, @patrickvale solution worked fine.
