### ISSUE TITLE
dm-test-swarm.sh doesn't work if `--virtualbox-memory 512` is set

### ISSUE THREAD

**Issue by tombusby** [vfarcic/cloud-provisioning#23]
I've tried this on my mac and on my linux box.

In both cases it just hangs at "waiting for an IP" and the docker-machine is never provisioned.

**Comment by vfarcic** [comment]
You're right. It seems that one of the recent releases become heavier and cannot operate on 500MB anymore. I removed `--virtualbox-memory` arguments so the scripts will created VMs with default memory (1GB).
