### ISSUE TITLE
DevOpts2.1: Using Packer To Create Amazon Machine Images (AMIs)

### ISSUE THREAD

**Issue by eig-cutter** [vfarcic/cloud-provisioning#3]
Hi Viktor,

As always, Thank you sir for your hard work and great books. I've run into an issue though...

The first instruction in the "Using Packer To Create Amazon Machine Images (AMIs)" section of the book is to change to a specific directory [_from root: vfarcic/cloud-provisioning_]

`cd terraform/aws`

However, the 'aws' directory doesn't exist. Is this a typo, or, is a directory missing?

**Comment by vfarcic** [comment]
Hi,

That's a typo. I just published a new version of the book with corrections
(it'll be available in 5 minutes) and pushed changes to the code in the
vfarcic/cloud-provisioning repo.

Can you pull the latest code and download the latest book release?

**Comment by eig-cutter** [comment]
Yes, I will do. Thanks so much for your always prompt and kind help :)
