### ISSUE TITLE
AWS related Packer Scripts failing to provision AMIs

### ISSUE THREAD

**Issue by eig-cutter** [vfarcic/cloud-provisioning#4]
I have run the Packer Build command against the various Packer json files in the "terraform/aws" and the "terrform/aws-full" directories and I encountered the same error with each one... resulting in build termination and no AMI image existing for any of them:

**Error:**
_"amazon-ebs: E: can not open /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_InRelease - fopen (2: No such file or directory)"_

**Recommend:**
Upon adding the "sudo apt-get clean" command to the "provisioners : inline" section for each of the Packer json files I was able to get them to build correctly.

**Example:**
`"provisioners": [{
    "type": "shell",
    "inline": [
      "sudo apt-get clean",
      "sudo apt-get update",
      "sudo apt-get install -y apt-transport-https ca-certificates nfs-common",
      "sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D",
      "echo 'deb https://apt.dockerproject.org/repo ubuntu-xenial main' | sudo tee /etc/apt/sources.list.d/docker.list",
      "sudo apt-get update",
      "sudo apt-get install -y docker-engine",
      "sudo usermod -aG docker ubuntu",
      "sudo curl -L \"https://github.com/docker/compose/releases/download/1.8.1/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose",
      "sudo chmod +x /usr/local/bin/docker-compose"
    ]
  }]`

**Comment by vfarcic** [comment]
Thanks for the tip. I added `sudo apt-get clean` to Packer JSON files.

P.S. aws-full directory will be used later on in the chapter about stateful services.
