### ISSUE TITLE
terraform error on digitalocean_droplet example

### ISSUE THREAD

**Issue by vitor-caetano** [vfarcic/cloud-provisioning#5]
The following fails for the current Digital Ocean terraform source:

$ terraform plan
...
Error running plan: 2 error(s) occurred:

* Resource 'digitalocean_droplet.swarm-manager' not found for variable 'digitalocean_droplet.swarm-manager.2.id'
* Resource 'digitalocean_droplet.swarm-manager' not found for variable 'digitalocean_droplet.swarm-manager.1.id'

**Comment by vitor-caetano** [comment]
The above fails with the latest terraform 0.8.1.
But it works on the previous version 0.7.13.

**Comment by vfarcic** [comment]
Thank you for letting me know this. The latest Terraform release contains a bug. An update of the book with the workaround will be released in a few minutes.
